### ISSUE TITLE
Reduce number of dependencies

### ISSUE THREAD

**Issue by ulf85** [tnagler/VineCopula#10]
Hi,

I would like to reduce the number of packages we rely on. Do we realy need them all?
Can we transfer some of them to "Suggest"?
For which function do we need "methods" or "grDevices"?

Best
Ulf

**Comment by tnagler** [comment]
Below, I list (to the best of my knowledge) the purpose of each package we depend on:
- "grDevices": provides color pallettes and functions for color manipulation. This is a very soft dependency since it is pre-installed on basically any machine. As of R-3.3 such packages have to be stated explicitly due to more thorough CRAN checks (same holds for "graphics", "utils" and "stats").
- "MASS": used for 
  - `ginv` (generalized inverse of a matrix) in `BiCopGofTest`
  - bivariate kernel density estimation in `BiCopMetaContour`. In the medium run, we may want to replace this by a dependency to my other package ["kdecopula"](https://github.com/tnagler/kdecopula). It gives much better kernel denstiy estimates and there shouldn't be any problems with the maintainer ;)
- "mvtnorm": I guess, this is used for the Gaussian copula?
- "network": plotting trees.
- "methods" and "copula": used for the interface to the copula package.
- "ADGofTest": Anderson-Darling GoF-test.
- "lattice": perspective plots (look better than `persp`).
- "doParallel", "parallel", "foreach": parallel computing.
