### ISSUE TITLE
Parallel computing in RVineStructureSelect slower than one core

### ISSUE THREAD

**Issue by spotopt** [tnagler/VineCopula#23]
Selecting a R-vine structure with several cores takes much longer than using just one. I used:
rvine <- RVineStructureSelect(data=U,  familyset=c(1),type=0, selectioncrit = "AIC",
                                  indeptest = FALSE,treecrit = "tau",
                                  trunclevel = NA,cores=4)
and U has 200+ dimensions.
The same holds if I truncate some trees. Is there an explanation for that?

**Comment by tnagler** [comment]
The explanation is rather simple (and not very satsfying):

 `RVineStructureSelect` uses `foreach` for parallelization which (as any method for parallelization in R) causes a substantial overhead. The overhead comes from setting up multiple instances of R, organizing the workload for each instance of R, and gathering the results. When the computations that are executed in parallel are very fast, the overhead caused by `foeach` can exceed the time saved through parallelization. 

This is exactly what happens in your example. Since you're using `familyset = 1`, the selection of each pair-copula (the task that is executed in parallel) is extremely fast. If you run the same command with `familyset = NA` or `familyset = 1:10`, the parallel version is probably faster.

**Comment by spotopt** [comment]
Thank you very much for the fast reply. Maybe a future release could avoid that by setting the maximum number of cores less or equal to the number of copula types. Another option is to add a comment in the package description. 
(Anyway, I am having lots of fun with this package. Thanks!)

**Comment by tnagler** [comment]
I would rather not tamper with the user specification of `cores`. But I added an remark to the documentation of the `cores` argument (see 67829e6).
