### ISSUE TITLE
Error with function BiCopSelect()

### ISSUE THREAD

**Issue by heshuli** [tnagler/VineCopula#39]
I used BiCopSelect() to select a copula, the code is:

fit <- BiCopSelect(px[ , 1], py[ , 1], familyset = 3:5, rotations = FALSE)

And the function reported an error like:

Error in if (c11 - c00 > 0.3) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In cor(x[(x[, 1] < 0) & (x[, 2] < 0), ]) : 标准差为零

Is there any problem with the data I use? Thanks a lot.

**Comment by tnagler** [comment]
Could you check if you have the latest version of VineCopula installed (v 2.1.2)?

**Comment by heshuli** [comment]
Mine is 2.0.6. I will try the latest one. Thanks.

**Comment by heshuli** [comment]
It helps. There is no error now and the value seems to be good but there is still a warning message:

In cor(x[(x[, 1] < 0) & (x[, 2] < 0), ]) : The standard error is zero.

**Comment by tnagler** [comment]
Yeah this usually happens because of one of three reasons:
1. The sample size is very small. There's nothing wrong with that.
2. The data is (almost) perfectly correlated. When the dependence is in fact perfect, you should eliminate one of the variables. Otherwise there's nothing to worry about.
3. The data is not sufficiently uniform. This is either because the marginal distributions have not been handled properly or some variable is discrete. In either case, you need to rethink your model because important assumptions are not met.
