### ISSUE TITLE
Testing suite for all functions in the package

### ISSUE THREAD

**Issue by tnagler** [tnagler/VineCopula#6]
The output of all functions in the package should be automatically tested (no `NA`/`NaN`/`Inf`/etc).

**Comment by ulf85** [comment]
Worked on that yesterday. Now new tests for BiCopCDF and BiCopPDF.
Problem: Memory usage is quite high.
Cause: big arrays

**Comment by tnagler** [comment]
Two suggestions:
- Use expand.grid(u1, u2) instead of looping through u1
- For each family/parameter combination, just store the sum of the results. This safes alot of memory and leads to the same conclusion: `any(is.na(results))` is equivalent to `is.na(sum(res))` etc.

**Comment by ulf85** [comment]
Thanks for the suggestions.
- I did not know that function. I also wanted to avoit the for loops since I wanted to minimize the number of calls of C from R. And C-Code is faster than R for-loops. `expand.grid()` is doing exactly what I was intendet to do next to use only vectors instead of for-loops. Thus, thanks.
- if I want to know which combination fails, I need all results. But for the check-function I can use your suggestion to use `is.na(sum(results))` or `!is.finite(sum(results))`  (is.finite checks is.na(), is.nan() and is.finite() ). The check function also needed a lot of memory and computation time. I guess `sum()` is much quicker than the check for each observation.

**Comment by tnagler** [comment]
I would just store which family/parameter combination fails. If one fails, we can easily search for the  u1/u2 combination that caused the failure .

**Comment by ulf85** [comment]
I guess I got it now. We aggregate over the u1 and u2 and have only one value for each family and parameter combination. In case of failture we start the function again for all u1 and u2 combinations for that specific family/parameter combination.
That is a good idea. Thanks.

**Comment by tnagler** [comment]
Probably not going to happen, I close for now.
